/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function ChessSet(props) {
  const { nodes, materials } = useGLTF("/GLTF/ChessSetObject.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chessboard_1.geometry}
        material={materials["White Squares"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chessboard_2.geometry}
        material={materials["Black Squares"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Chessboard_3.geometry}
        material={materials["Board Base"]}
      />
      <group
        position={[-0.209821, 0.17200001, 0]}
        rotation={[-Math.PI, 0, 0]}
        scale={-0.025}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Bishop_1.geometry}
          material={materials["Black Pieces"]}
          position={[0.01033878, -6.88000011, 3.5885663]}
          rotation={[0, 0, -Math.PI]}
          scale={-40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Bishop_2.geometry}
          material={materials["Black Pieces"]}
          position={[0.01033878, -6.88000011, -3.61143303]}
          rotation={[0, 0, -Math.PI]}
          scale={-40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_King.geometry}
          material={materials["Black Pieces"]}
          position={[0.01033878, -6.88000011, 1.18856645]}
          rotation={[-Math.PI, 0, 0]}
          scale={-40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Knight_1.geometry}
          material={materials["Black Pieces"]}
          position={[0.01033878, -6.88000011, 5.9885664]}
          rotation={[-Math.PI, Math.PI / 2, 0]}
          scale={-40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Knight_2.geometry}
          material={materials["Black Pieces"]}
          position={[0.01033878, -6.88000011, -6.01143312]}
          rotation={[-Math.PI, Math.PI / 2, 0]}
          scale={-40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Pawn_1.geometry}
          material={materials["Black Pieces"]}
          position={[-2.38966179, -6.88000011, 8.38856602]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Pawn_2.geometry}
          material={materials["Black Pieces"]}
          position={[-2.38966179, -6.88000011, 5.9885664]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Pawn_3.geometry}
          material={materials["Black Pieces"]}
          position={[-2.38966179, -6.88000011, 3.58856654]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Pawn_4.geometry}
          material={materials["Black Pieces"]}
          position={[-2.38966179, -6.88000011, 1.18856645]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Pawn_5.geometry}
          material={materials["Black Pieces"]}
          position={[-2.38966179, -6.88000011, -1.21143341]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Pawn_6.geometry}
          material={materials["Black Pieces"]}
          position={[-2.38966179, -6.88000011, -3.61143351]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Pawn_7.geometry}
          material={materials["Black Pieces"]}
          position={[-2.38966179, -6.88000011, -6.0114336]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Pawn_8.geometry}
          material={materials["Black Pieces"]}
          position={[-2.38966179, -6.88000011, -8.41143417]}
          rotation={[-Math.PI, 0, 0]}
          scale={-0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Queen.geometry}
          material={materials["Black Pieces"]}
          position={[0.01033878, -6.88000011, -1.21143353]}
          rotation={[-Math.PI, 0, 0]}
          scale={-40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Rook_1.geometry}
          material={materials["Black Pieces"]}
          position={[0.01033878, -6.88000011, 8.38856602]}
          rotation={[-Math.PI, 0, 0]}
          scale={-40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Black_Rook_2.geometry}
          material={materials["Black Pieces"]}
          position={[0.01033878, -6.88000011, -8.41143322]}
          rotation={[-Math.PI, 0, 0]}
          scale={-40}
        />
      </group>
      <group position={[0.209821, 0.17200001, 0]} scale={0.025}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Bishop_1.geometry}
          material={materials["White Pieces"]}
          position={[0.0039835, -6.88000011, 3.5885663]}
          scale={40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Bishop_2.geometry}
          material={materials["White Pieces"]}
          position={[0.0039835, -6.88000011, -3.61143303]}
          scale={40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_King.geometry}
          material={materials["White Pieces"]}
          position={[0.0039835, -6.88000011, 1.18856645]}
          scale={40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Knight_1.geometry}
          material={materials["White Pieces"]}
          position={[0.0039835, -6.88000011, 5.9885664]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Knight_2.geometry}
          material={materials["White Pieces"]}
          position={[0.0039835, -6.88000011, -6.01143312]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Pawn_1.geometry}
          material={materials["White Pieces"]}
          position={[-2.3960166, -6.88000011, 8.38856602]}
          scale={0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Pawn_2.geometry}
          material={materials["White Pieces"]}
          position={[-2.3960166, -6.88000011, 5.9885664]}
          scale={0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Pawn_3.geometry}
          material={materials["White Pieces"]}
          position={[-2.3960166, -6.88000011, 3.58856654]}
          scale={0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Pawn_4.geometry}
          material={materials["White Pieces"]}
          position={[-2.3960166, -6.88000011, 1.18856645]}
          scale={0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Pawn_5.geometry}
          material={materials["White Pieces"]}
          position={[-2.3960166, -6.88000011, -1.21143341]}
          scale={0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Pawn_6.geometry}
          material={materials["White Pieces"]}
          position={[-2.3960166, -6.88000011, -3.61143351]}
          scale={0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Pawn_7.geometry}
          material={materials["White Pieces"]}
          position={[-2.3960166, -6.88000011, -6.0114336]}
          scale={0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Pawn_8.geometry}
          material={materials["White Pieces"]}
          position={[-2.3960166, -6.88000011, -8.41143417]}
          scale={0.59999996}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Queen.geometry}
          material={materials["White Pieces"]}
          position={[0.0039835, -6.88000011, -1.21143353]}
          scale={40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Rook_1.geometry}
          material={materials["White Pieces"]}
          position={[0.0039835, -6.88000011, 8.38856602]}
          scale={40}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.White_Rook_2.geometry}
          material={materials["White Pieces"]}
          position={[0.0039835, -6.88000011, -8.41143322]}
          scale={40}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/GLTF/ChessSetObject.gltf");
