/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Dungeon(props) {
  const { nodes, materials } = useGLTF("/GLTF/Dungeon.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel001.geometry}
        material={materials["Colour Grid"]}
        position={[8.66, 0.61, -3.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel002.geometry}
        material={materials["Colour Grid"]}
        position={[10.95, 0.61, -8.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel003.geometry}
        material={materials["Colour Grid"]}
        position={[12.46, 0.61, -8.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Barrel004.geometry}
        material={materials["Colour Grid"]}
        position={[11.66, 1.81, -8.14]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crate001.geometry}
        material={materials["Colour Grid"]}
        position={[12.58, 0.62, -5.38]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crate002.geometry}
        material={materials["Colour Grid"]}
        position={[13, 0.62, -4.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crate003.geometry}
        material={materials["Colour Grid"]}
        position={[12.35, 1.85, -4.67]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crate004.geometry}
        material={materials["Colour Grid"]}
        position={[12.66, 0.97, -2.7]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment001.geometry}
        material={materials["Colour Grid"]}
        position={[2, 0, -14.1]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment002.geometry}
        material={materials["Colour Grid"]}
        position={[-2, 0, -14.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment003.geometry}
        material={materials["Colour Grid"]}
        position={[-2, 0, -10.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment005.geometry}
        material={materials["Colour Grid"]}
        position={[-2, 0, -2.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment006.geometry}
        material={materials["Colour Grid"]}
        position={[-2, 0, 1.9]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment007.geometry}
        material={materials["Colour Grid"]}
        position={[2, 0, 1.9]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment008.geometry}
        material={materials["Colour Grid"]}
        position={[6, 0, 1.9]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment009.geometry}
        material={materials["Colour Grid"]}
        position={[10, 0, 1.9]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment010.geometry}
        material={materials["Colour Grid"]}
        position={[14, 0, 1.9]}
        rotation={[0, -1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment011.geometry}
        material={materials["Colour Grid"]}
        position={[14, 0, -2.1]}
        rotation={[0, -1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment012.geometry}
        material={materials["Colour Grid"]}
        position={[14, 0, -6.1]}
        rotation={[0, -1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment013.geometry}
        material={materials["Colour Grid"]}
        position={[14, 0, -10.1]}
        rotation={[0, -1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment014.geometry}
        material={materials["Colour Grid"]}
        position={[14, 0, -14.1]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment004.geometry}
        material={materials["Colour Grid"]}
        position={[6, 0, -14.1]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment015.geometry}
        material={materials["Colour Grid"]}
        position={[6, 0, -18.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment016.geometry}
        material={materials["Colour Grid"]}
        position={[6, 0, -22.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment017.geometry}
        material={materials["Colour Grid"]}
        position={[6, 0, -30.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment018.geometry}
        material={materials["Colour Grid"]}
        position={[6, 0, -34.1]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment019.geometry}
        material={materials["Colour Grid"]}
        position={[10, 0, -34.1]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment020.geometry}
        material={materials["Colour Grid"]}
        position={[10, 0, -30.1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment021.geometry}
        material={materials["Colour Grid"]}
        position={[10, 0, -26.1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment022.geometry}
        material={materials["Colour Grid"]}
        position={[10, 0, -22.1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment023.geometry}
        material={materials["Colour Grid"]}
        position={[10, 0, -18.1]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment024.geometry}
        material={materials["Colour Grid"]}
        position={[2, 0, -22.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment025.geometry}
        material={materials["Colour Grid"]}
        position={[-2, 0, -22.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment026.geometry}
        material={materials["Colour Grid"]}
        position={[-6, 0, -22.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment027.geometry}
        material={materials["Colour Grid"]}
        position={[-10, 0, -22.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment028.geometry}
        material={materials["Colour Grid"]}
        position={[-6, 0, -26.1]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment029.geometry}
        material={materials["Colour Grid"]}
        position={[-2, 0, -26.1]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment030.geometry}
        material={materials["Colour Grid"]}
        position={[2, 0, -26.1]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment031.geometry}
        material={materials["Colour Grid"]}
        position={[-10, 0, -30.1]}
        rotation={[0, 1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment032.geometry}
        material={materials["Colour Grid"]}
        position={[-14, 0, -30.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment033.geometry}
        material={materials["Colour Grid"]}
        position={[-18, 0, -30.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment034.geometry}
        material={materials["Colour Grid"]}
        position={[-22, 0, -30.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment035.geometry}
        material={materials["Colour Grid"]}
        position={[-22, 0, -26.1]}
        rotation={[0, -1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment036.geometry}
        material={materials["Colour Grid"]}
        position={[-22, 0, -22.1]}
        rotation={[0, -1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment037.geometry}
        material={materials["Colour Grid"]}
        position={[-22, 0, -18.1]}
        rotation={[0, -1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment038.geometry}
        material={materials["Colour Grid"]}
        position={[-18, 0, -18.1]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment039.geometry}
        material={materials["Colour Grid"]}
        position={[-14, 0, -18.1]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment040.geometry}
        material={materials["Colour Grid"]}
        position={[-10, 0, -18.1]}
        rotation={[0, -1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment041.geometry}
        material={materials["Colour Grid"]}
        position={[-6, 0, -2.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment042.geometry}
        material={materials["Colour Grid"]}
        position={[-10, 0, -2.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment043.geometry}
        material={materials["Colour Grid"]}
        position={[-10, 0, -6.1]}
        rotation={[0, 1.57, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Segment044.geometry}
        material={materials["Colour Grid"]}
        position={[-6, 0, -6.1]}
        rotation={[Math.PI, 0, Math.PI]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Original001.geometry}
        material={materials["Colour Grid"]}
        position={[10, 1, -16]}
        rotation={[0, Math.PI / 2, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Original002.geometry}
        material={materials["Colour Grid"]}
        position={[4, 1, -26]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Original003.geometry}
        material={materials["Colour Grid"]}
        position={[-12, 1, -18]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Wall_Original004.geometry}
        material={materials["Colour Grid"]}
        position={[-8, 1, -6]}
        rotation={[Math.PI, 0, Math.PI]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Doorway001.geometry}
        material={materials["Colour Grid"]}
        position={[-2, 0, -6]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Doorway002.geometry}
        material={materials["Colour Grid"]}
        position={[10, 0, -14]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Doorway003.geometry}
        material={materials["Colour Grid"]}
        position={[6, 0, -26]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Doorway004.geometry}
        material={materials["Colour Grid"]}
        position={[-10, 0, -26]}
        rotation={[0, Math.PI / 2, 0]}
        scale={[1.01, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch001.geometry}
        material={materials["Colour Grid"]}
        position={[0, 1.53, 1.71]}
        rotation={[-0.29, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch003.geometry}
        material={materials["Colour Grid"]}
        position={[8, 1.53, 1.66]}
        rotation={[-0.29, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch002.geometry}
        material={materials["Colour Grid"]}
        position={[13.81, 1.53, -0.15]}
        rotation={[0, 0, 0.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch004.geometry}
        material={materials["Colour Grid"]}
        position={[13.83, 1.53, -8.15]}
        rotation={[0, 0, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch005.geometry}
        material={materials["Colour Grid"]}
        position={[12.01, 1.53, -13.89]}
        rotation={[0.28, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch006.geometry}
        material={materials["Colour Grid"]}
        position={[4.01, 1.53, -13.92]}
        rotation={[0.24, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch007.geometry}
        material={materials["Colour Grid"]}
        position={[-1.82, 1.53, -12.05]}
        rotation={[0, 0, -0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch008.geometry}
        material={materials["Colour Grid"]}
        position={[-8.02, 1.53, -5.82]}
        rotation={[0.25, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch009.geometry}
        material={materials["Colour Grid"]}
        position={[-8.02, 1.53, -2.27]}
        rotation={[-0.25, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch011.geometry}
        material={materials["Colour Grid"]}
        position={[6.19, 1.53, -16.03]}
        rotation={[0, 0, -0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch012.geometry}
        material={materials["Colour Grid"]}
        position={[9.81, 1.53, -16.03]}
        rotation={[0, 0, 0.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch013.geometry}
        material={materials["Colour Grid"]}
        position={[9.82, 1.53, -24.03]}
        rotation={[0, 0, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch014.geometry}
        material={materials["Colour Grid"]}
        position={[9.83, 1.53, -32.03]}
        rotation={[0, 0, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch015.geometry}
        material={materials["Colour Grid"]}
        position={[6.18, 1.53, -32.03]}
        rotation={[0, 0, -0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch016.geometry}
        material={materials["Colour Grid"]}
        position={[4, 1.53, -25.83]}
        rotation={[0.26, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch017.geometry}
        material={materials["Colour Grid"]}
        position={[4, 1.53, -22.26]}
        rotation={[-0.18, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch018.geometry}
        material={materials["Colour Grid"]}
        position={[-4, 1.53, -25.93]}
        rotation={[0.25, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch019.geometry}
        material={materials["Colour Grid"]}
        position={[-4, 1.53, -22.26]}
        rotation={[-0.18, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch020.geometry}
        material={materials["Colour Grid"]}
        position={[-12, 1.53, -29.92]}
        rotation={[0.26, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch021.geometry}
        material={materials["Colour Grid"]}
        position={[-12, 1.53, -18.18]}
        rotation={[-0.24, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch022.geometry}
        material={materials["Colour Grid"]}
        position={[-20, 1.53, -29.93]}
        rotation={[0.27, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch023.geometry}
        material={materials["Colour Grid"]}
        position={[-20, 1.53, -18.26]}
        rotation={[-0.16, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch024.geometry}
        material={materials["Colour Grid"]}
        position={[-21.84, 1.53, -24.1]}
        rotation={[0, 0, -0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tile_Set_1001.geometry}
        material={materials["Colour Grid"]}
        position={[7.88, 0.01, -8.41]}
        rotation={[0, 0, -0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tile_Set_1002.geometry}
        material={materials["Colour Grid"]}
        position={[7.64, 0.01, -27.28]}
        rotation={[0, 1.01, -0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tile_Set_1003.geometry}
        material={materials["Colour Grid"]}
        position={[2.74, 0.01, -1.97]}
        rotation={[Math.PI, -0.9, 3.12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tile_Set_1004.geometry}
        material={materials["Colour Grid"]}
        position={[-13.46, 0.01, -21.35]}
        rotation={[0, -0.53, -0.03]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tile_Set_2001.geometry}
        material={materials["Colour Grid"]}
        position={[8.45, 0, -19.36]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tile_Set_2002.geometry}
        material={materials["Colour Grid"]}
        position={[-17.62, 0, -25.13]}
        rotation={[0, -0.74, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tile_Set_3001.geometry}
        material={materials["Colour Grid"]}
        position={[10.63, 0, -2.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Tile_Set_3002.geometry}
        material={materials["Colour Grid"]}
        position={[-5.36, 0, -24.51]}
        rotation={[0, -1.17, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={materials["Colour Grid"]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials["Colour Grid"]}
        position={[4, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane002.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane003.geometry}
        material={materials["Colour Grid"]}
        position={[12, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane004.geometry}
        material={materials["Colour Grid"]}
        position={[0, 0, -4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane005.geometry}
        material={materials["Colour Grid"]}
        position={[4, 0, -4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane006.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, -4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane007.geometry}
        material={materials["Colour Grid"]}
        position={[12, 0, -4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane008.geometry}
        material={materials["Colour Grid"]}
        position={[0, 0, -8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane009.geometry}
        material={materials["Colour Grid"]}
        position={[4, 0, -8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane010.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, -8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane011.geometry}
        material={materials["Colour Grid"]}
        position={[12, 0, -8]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane012.geometry}
        material={materials["Colour Grid"]}
        position={[0, 0, -12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane013.geometry}
        material={materials["Colour Grid"]}
        position={[4, 0, -12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane014.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, -12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane015.geometry}
        material={materials["Colour Grid"]}
        position={[12, 0, -12]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane016.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, -16]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane017.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, -20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane018.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, -20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane019.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, -24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane020.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, -28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane021.geometry}
        material={materials["Colour Grid"]}
        position={[8, 0, -32]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane022.geometry}
        material={materials["Colour Grid"]}
        position={[4, 0, -24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane023.geometry}
        material={materials["Colour Grid"]}
        position={[0, 0, -24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane024.geometry}
        material={materials["Colour Grid"]}
        position={[-4, 0, -24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane025.geometry}
        material={materials["Colour Grid"]}
        position={[-8, 0, -24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane026.geometry}
        material={materials["Colour Grid"]}
        position={[-12, 0, -24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane027.geometry}
        material={materials["Colour Grid"]}
        position={[-12, 0, -20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane028.geometry}
        material={materials["Colour Grid"]}
        position={[-16, 0, -20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane029.geometry}
        material={materials["Colour Grid"]}
        position={[-20, 0, -20]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane030.geometry}
        material={materials["Colour Grid"]}
        position={[-16, 0, -24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane031.geometry}
        material={materials["Colour Grid"]}
        position={[-16, 0, -28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane032.geometry}
        material={materials["Colour Grid"]}
        position={[-12, 0, -28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane033.geometry}
        material={materials["Colour Grid"]}
        position={[-20, 0, -24]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane034.geometry}
        material={materials["Colour Grid"]}
        position={[-20, 0, -28]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane035.geometry}
        material={materials["Colour Grid"]}
        position={[-4, 0, -4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane036.geometry}
        material={materials["Colour Grid"]}
        position={[-8, 0, -4]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame001.geometry}
        material={materials["Colour Grid Emission"]}
        position={[0, 1.84, 1.62]}
        rotation={[-0.29, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame003.geometry}
        material={materials["Colour Grid Emission"]}
        position={[8, 1.84, 1.56]}
        rotation={[-0.29, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame002.geometry}
        material={materials["Colour Grid Emission"]}
        position={[13.71, 1.84, -0.15]}
        rotation={[0, 0, 0.33]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame004.geometry}
        material={materials["Colour Grid Emission"]}
        position={[13.75, 1.84, -8.15]}
        rotation={[0, 0, 0.25]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame005.geometry}
        material={materials["Colour Grid Emission"]}
        position={[12.01, 1.84, -13.8]}
        rotation={[0.28, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame006.geometry}
        material={materials["Colour Grid Emission"]}
        position={[4.01, 1.84, -13.84]}
        rotation={[0.24, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame007.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-1.72, 1.84, -12.05]}
        rotation={[0, 0, -0.31]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame008.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-8.02, 1.84, -5.74]}
        rotation={[0.25, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame009.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-8.02, 1.84, -2.34]}
        rotation={[-0.25, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame010.geometry}
        material={materials["Colour Grid Emission"]}
        position={[6.27, 1.84, -16.03]}
        rotation={[0, 0, -0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame011.geometry}
        material={materials["Colour Grid Emission"]}
        position={[9.75, 1.84, -16.03]}
        rotation={[0, 0, 0.18]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame012.geometry}
        material={materials["Colour Grid Emission"]}
        position={[9.75, 1.84, -24.03]}
        rotation={[0, 0, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame013.geometry}
        material={materials["Colour Grid Emission"]}
        position={[9.76, 1.84, -32.03]}
        rotation={[0, 0, 0.22]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame014.geometry}
        material={materials["Colour Grid Emission"]}
        position={[6.24, 1.84, -32.03]}
        rotation={[0, 0, -0.21]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame015.geometry}
        material={materials["Colour Grid Emission"]}
        position={[4, 1.84, -25.75]}
        rotation={[0.26, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame016.geometry}
        material={materials["Colour Grid Emission"]}
        position={[4, 1.84, -22.32]}
        rotation={[-0.18, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame017.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-4, 1.84, -25.85]}
        rotation={[0.25, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame018.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-4, 1.84, -22.32]}
        rotation={[-0.18, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame019.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-12, 1.84, -29.84]}
        rotation={[0.26, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame020.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-12, 1.84, -18.25]}
        rotation={[-0.24, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame021.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-20, 1.84, -29.84]}
        rotation={[0.27, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame022.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-20, 1.84, -18.31]}
        rotation={[-0.16, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torch_Flame023.geometry}
        material={materials["Colour Grid Emission"]}
        position={[-21.77, 1.84, -24.09]}
        rotation={[0, 0, -0.19]}
      />
    </group>
  );
}

useGLTF.preload("/GLTF/Dungeon.glb");
